package Physics.ElectricalDiagram;

import Algebra.Fraction;

public interface CircuitComponent {
    /**
     * Finds the net resistance generated by this CircuitComponent
     * @return the net resistance
     */
    //Fraction getResistance();

    /**
     * Finds the net current traversing this CircuitComponent
     * @return the net current
     */
    //Fraction getCurrent();
}
